### ISSUE TITLE
Nested Pod Styles

### ISSUE THREAD

**Issue by timkendall** [salsify/ember-css-modules#10]
I'm not sure that this supports nested pod components. For example, given the structure

```
/components
  /infinite-list
    -component.js
    -template.hbs
    -styles.css
    /list-item
      styles.css
      ...
```

I will receive the error `Uncaught Error: Failed to create an instance of 'styles:infinite-list/list-item'. Most likely an improperly defined class or an invalid module export.`  Am I doing something wrong?

**Comment by dfreeman** [comment]
We're using nested components with this addon in production, and I [just added a couple tests](https://github.com/salsify/ember-css-modules/commit/f9bdf5bde313eee45c09ed64c8343f8b4149ec2b) (which I actually thought already existed) to make sure those continue to work moving forward.

Based on that error, it looks as though the `ember-css-modules` initializer hasn't run. Can you provide any more details about your setup?

**Comment by timkendall** [comment]
So as mentioned in [#11](https://github.com/salsify/ember-css-modules/issues/11), my Ember Engines setup was likely what was causing issues. Everything seems to work now after restarting Ember server. Thanks for adding the tests. We can probably close this issue!

**Comment by dfreeman** [comment]
Incidentally, the normalized project structure proposed in https://github.com/emberjs/rfcs/pull/124 would eliminate the need to manually import `styles` (and `template`) in addons – it'll be great to be able to get rid of that particular gotcha.
