### ISSUE TITLE
Please publish v1.0.0-beta.1

### ISSUE THREAD

**Issue by fpauser** [salsify/ember-css-modules#112]
Please publish v1.0.0-beta.1

**Comment by fpauser** [comment]
Ah, yes, you are right, it is already published. Thought this could be the reason for this yarn error:
https://travis-ci.org/dfreeman/ember-css-modules-sass/jobs/426651610#L751

**Comment by buschtoens** [comment]
The linter is actually complaining because you are `require`ing a package that is only a [dev dependency](https://github.com/dfreeman/ember-css-modules-sass/blob/c61a50590b0dcad5e068e4ac8db5729ab58f1d21/package.json#L42).

**Comment by fpauser** [comment]
I'll try that - closing this issue as the version was propertly published.
