### ISSUE TITLE
Working with components using splat attributes 

### ISSUE THREAD

**Issue by josemarluedke** [salsify/ember-css-modules#116]
Hey there! Thanks for this awesome project.

I was hoping to use this project in combination with Angle Brackets Components and the splat attributes (`...attributes`) feature from Ember v3.4. In my tests, it doesn't seem to work as one would expect.

Here is my attempt:

```hbs
//my-component.hbs

<div
  class="my-component"
  local-class="my-local-class"
  ...attributes
>
  This is my-component
</div>
```

```hbs
// application.hbs

<MyComponent class="my-called-class" />
```

The current behavior is: No class end up in the HTML:

```html
<div class="my-called-class">
  This is my-component
</div>
```

Expected behavior, all the classes would be present:

```html
<div class="my-component _my-local-class_167kj3 my-called-class">
  This is my-component
</div>
```

Note, if I remove the `...attributes` from the component, css-modules will add the correct local class.

My test project can be found here: https://github.com/josemarluedke/--css-modules-test

**Comment by dfreeman** [comment]
Thanks for the report, @josemarluedke! I think there's some special casing around how `class` works with `...attributes`, and it may be that we're doing something that doesn't play nicely with that.

I can't make any promises, but I'll try and dig into this soon to understand what's happening and hopefully put a fix together 🙂

**Comment by josemarluedke** [comment]
@dfreeman Awesome! I just tested it out and it works as expected. 

Thank you for taking the time to fix this.
