### ISSUE TITLE
localClassNameBindings, and all decorators do not translate class to local version with hash

### ISSUE THREAD

**Issue by NullVoxPopuli** [salsify/ember-css-modules#119]
```ts
import Component from '@ember/component';

export default Component.extend({
  localClassNameBindings: ['isOpen:is-open']
});
```
```hbs
<div class={{local-class 'item'}} ...attributes>
  {{yield}}
</div>
```
when `isOpen` is set to true as an argument to this component, the class `is-open` is added to the div above, but with out the `x4tin`-style hash.

**Comment by dfreeman** [comment]
@NullVoxPopuli any chance you can point me at a working reproduction of this? I can't reproduce the behavior you're describing locally.

**Comment by NullVoxPopuli** [comment]
ah! so the issue is that localClassName/Bindings are for the root div AND since I was using a sparkles component, there is no root div. 

:D

**Comment by dfreeman** [comment]
For any future travelers who comes across this, `localClassNames` and `localClassNameBindings` are direct parallels to `classNames` and `classNameBindings`, so they only apply to the root element of your component (if there is one).
