### ISSUE TITLE
Weird decorator behaviour

### ISSUE THREAD

**Issue by Windvis** [salsify/ember-css-modules#122]
Hey guys,

We are using ember-css-modules in combination with ember-decorators and we ran in some weird issues. Exceptions are thrown due to seemingly random things. It's a combination of decorator order, setting a default value for the class field and passing params to the decorator.

I created a test repo with some more information: https://github.com/NindroidX/ember-css-modules-decorators-test more specifically in [this file](https://github.com/NindroidX/ember-css-modules-decorators-test/blob/master/app/components/test-component.js).

I'm pretty new to css modules and decorators so it's likely I'm doing something wrong.

**Comment by buschtoens** [comment]
Thank you for opening this issue and providing a reproduction repo! I'll try to take a look soon.

**Comment by dfreeman** [comment]
I suspect this may just be something we need to document better, but it's interesting that the `className` decorator doesn't have this same problem. With the whole ecosystem looking to move to the stage 2 decorators spec in the near future, this may make sense to revisit then.
