### ISSUE TITLE
Resolving classes from an addon, within an engine, does not work

### ISSUE THREAD

**Issue by alexlafroscia** [salsify/ember-css-modules#125]
I came across the need to resolve a class name from an addon today, and was delighted to see that, generally, this is supported!

https://github.com/salsify/ember-css-modules/blob/2e300294dd629bbb509c5f132ceb80f169196c62/lib/resolve-path.js#L40

However, I ran into an issue with Ember Engines that's blocking me from using this:

- The class I want to compose from is in an addon
- That addon is a dependency of an engine; the stylesheet that is trying to compose from the addon lives here
- That engine is mounted into my application; the application does not have a direct dependency on the addon (nor should it)

Within that `resolveExternal` function linked to above, `options.project` is pointing to the _application_ not the engine, so the `addon` can't be resolved.

The application does not have a direct dependency on that addon, and I don't want to introduce one, or we'll loose out on the benefits of lazy-loading that whole addon.

**Comment by alexlafroscia** [comment]
Huh! How about that!

A tiny bit of extra context, that likely isn't necessary but I forgot to include previously: this was what gave away the issue when I was digging into it earlier

<img width="1007" alt="screen shot 2018-11-06 at 4 11 33 pm" src="https://user-images.githubusercontent.com/1645881/48104053-ac0c1200-e1e6-11e8-88b6-6965d381231c.png">

the `ownerName` and the project aren't the same thing!

**Comment by dfreeman** [comment]
Yep. You may already know this, but "owner" in this code (which predates Ember's use of the word, but now it's kind of confusing) roughly means "the app or addon that ember-css-modules is acting on behalf of", while in Ember CLI `project` always refers to the root _thing_, comprised of the host app and its whole tree of addons.

I have some time blocked off tomorrow to do some cleanup here and try and make sure our Broccoli output is stable; I'll aim to get a fix for this in as well.

**Comment by alexlafroscia** [comment]
Sweet! I'm happy to work on the issue too (or with you) since we'd love to start composing classes from an addon this way in our engines.

**Comment by dfreeman** [comment]
Thanks for the offer! I ended up having @kehphin and @0xadada copilot on a bug squashing session this afternoon, and just published a fix in v1.0.3.
