### ISSUE TITLE
css not generated for 'tagless' components?

### ISSUE THREAD

**Issue by lougreenwood** [salsify/ember-css-modules#129]
Is it possible for a component which uses ECM to be tagless `tagName: ''`?

It seems that generation of styles is maybe skipped if the component is tagless - I get this error when attempting to use `local-class` in the tagless component template:

`Unable to resolve local class names from my-addon/styles/components/sc-card; does the styles file exist?`

**Comment by buschtoens** [comment]
Does the `addon/styles/components/sc-card.css` file actually exist?

**Comment by lougreenwood** [comment]
😄 .... so...

In this particular use case, no, the css file is actually `_sc-card.css` (I'm prefixing certain stylesheets to make sure they're included in earlier in the compiled stylesheet).

However, I have `_sc-card.css` referenced in the component:

```
import Component from '@ember/component'
import template from 'my-addon/templates/components/sc-card'
import styles from 'my-addon/ui/styles/components/_sc-card'
import { tagName, layout, classNames } from '@ember-decorators/component'

@tagName('')
@layout(template)
@classNames('card', styles['sc-card'])
export default class ScCardComponent extends Component {}
```

I assumed that local-class would use the `styles` property in the component, but I'm now guessing that it doesn't and instead tries to resolve a `/styles/components/*.css` which has the same filename as the component itself.

I'm also now seeing the styles compiled into the stylesheet, even if it's a tagless component. For now, the following works in my tagless component (since my css files use a prefixed variation of the component name):

```
import Component from '@ember/component'
import template from 'my-addon/templates/components/sc-card'
import styles from 'my-addon/ui/styles/components/_sc-card'
import { tagName, layout, classNames } from '@ember-decorators/component'

@tagName('')
@layout(template)
export default class ScCardComponent extends Component {
    styles = styles
}
```

```
<div class={{get this.styles "sc-card"}}>
    my tagless inner html
</div>
```

**Comment by buschtoens** [comment]
There is no need to to prefix the css files, because the whole point of css-modules is that order of inclusion should not matter. 😉 

Why do you need this file to be included first?
