### ISSUE TITLE
override order that .css files are imported in

### ISSUE THREAD

**Issue by lougreenwood** [salsify/ember-css-modules#130]
It seems that ECM is importing css files in alphabetical order.

However, if a component extends another component (both of which are managed by ECM), there's a risk that the implied specificity will be broken if the child component's name starts with a letter which is before the parent component's name:

``` css
.child-component { background-colour: red; }
```

``` css
.parent-component { background-colour: blue; }
```

```js 
Import ParentComponent from "./parent-component";

export default class ChildComponent extends ParentComponent {}
```

Results in the following HTML being rendered
```
<div class="child-component parent-component">
</div>
```

So far, so good - the problem is that because `parent-component.css` comes after `child-component.css`, it's injected lower down in the app.css stylesheet cascade and it's properties override `.child-component` - i.e `background-colour` will be blue.

The way I've solved this is to prefix the stylesheets for all of these 'parent-like' components, something  like:
* `_parent-component.css`
* `child-component.css`

I then import the styles into the component like this:
```
import Component from '@ember/component'
import template from 'my-addon/templates/components/parent-component'
import styles from 'my-addon/styles/components/_parent-component'
import { layout, classNames } from '@ember-decorators/component'

@layout(template)
@classNames(styles['parent-component'])
export default class ParentComponent extends Component {}
```

However this seems to cause other issues (like `local-class` doesn't work because the css file name doesn't match the component, so the css isn't found. (#129))

So, I wonder if it's possible to define specific css files (or even better, define patterns for filenames) which should be placed at the end of the stylesheet rather than inline according to the alphabetical ordering of the component name.

**Comment by dfreeman** [comment]
@lougreenwood check out https://github.com/salsify/ember-css-modules/blob/master/docs/ORDERING.md for details on how modules are ordered. You could set `headerModules` and `footerModules` explicitly, or you could introduce a dummy `@value` dependency from your child to your parent to ensure it's emitted later.

**Comment by lougreenwood** [comment]
@dfreeman perfect, thanks, this looks like exactly what I need!

Does header/footerModules support wildcards etc?

**Comment by dfreeman** [comment]
Sorry I missed your question, @lougreenwood! As you probably discovered, `headerModules` and `footerModules` don't support globbing, mainly for perf/technical reasons.

**Comment by lougreenwood** [comment]
@dfreeman Damn, that's a shame - for our use case it means that what would be a nice concise 5-line set of definitions for the footer component becomes a 30-line long definition to catch all of the nested components.

Thanks for clarifying though!
