### ISSUE TITLE
should merge with `class` from splatributes

### ISSUE THREAD

**Issue by luxferresum** [salsify/ember-css-modules#133]
With splatributes the expected behaviour would be to merge incoming a `class` with a `local-class` declaration. However this does not work.

So having `my-component`:

    <div ...attributes local-class="foo"></div>

This will work as expected:

    <MyComponent local-class="bar" />

But this will override the local `foo` class:

    <MyComponent class="bar" />

This es especially annoying for tests when we test if splatributes is used and if a certain local class is also applied.

**Comment by dfreeman** [comment]
I'm not able to reproduce this—using any combination of `class` and `local-class` in the two templates shows both classes that I would expect in the final output; see [this sandbox](https://codesandbox.io/s/01mvq5qyll).

**Comment by luxferresum** [comment]
[I was able to reproduce a problem but this time the other way around.](https://github.com/luxferresum/ember-css-modules-splatributes).
However the problem is now also with a normal `class` inside and outside. So it seems to be no ECM problem.

So only the last has the inner `class`:

```
<MyComponent class="outer-class" />
<MyComponent local-class="outer-local-class" />
<MyComponent />
```

**Comment by dfreeman** [comment]
If you're seeing this with only `class`, it sounds like it's a bug somewhere upstream in Ember/Glimmer rather than with ECM 🤔

**Comment by dfreeman** [comment]
@luxferresum I'm going to go ahead and close this issue since it doesn't sound like it's specific to this addon, but please feel free to comment/reopen if that turns out not to be the case.
