### ISSUE TITLE
Integration tests are broken when using ember-css-modules

### ISSUE THREAD

**Issue by Dremora** [salsify/ember-css-modules#14]
The following exception gets thrown:
```
Uncaught Error: Failed to create an instance of 'styles:components/my-component'. Most likely an improperly defined class or an invalid module export.
```

This is probably caused by the fact that the initializer never gets called. Unit tests are likely broken as well, though I didn't test it.

**Comment by dfreeman** [comment]
This should be fixed in 0.3.0; please let me know if you continue to run into any issues in integration tests.
