### ISSUE TITLE
Styling active LinkTo 

### ISSUE THREAD

**Issue by joelamb** [salsify/ember-css-modules#147]
Hi, trying out ember-css-modules and struggling to see how I can access and style the auto-generated `class="active"` on the `<LinkTo>` component.
Declaring  `a.active` in my css works fine if I work with regular css, but has no effect, when using ember-css-modules.
Any help most welcome, thank you.

**Comment by buschtoens** [comment]
> ### Global Classes
>
>Some libraries provide explicit class names as part of their public interface in order to allow customization of their look and feel. If, for example, you're wrapping such a library in a component, you need to be able to reference those unscoped class names in the context of your component styles. The `:global` pseudoselector allows for this:
>
>```css
>.my-component :global(.some-library-class) {
>   color: orange;
>}
>```
>
>For more details on `:local` and `:global` exceptions, see [the CSS Modules documentation](https://github.com/css-modules/css-modules#exceptions).

— [Global Classes](https://github.com/salsify/ember-css-modules#global-classes)

This means, you could do something like this:

```css
.my-link:global(.active) {
  color: red;
}
```

```hbs
<LinkTo @route="photos" local-class="my-link">
  Photos
</LinkTo>
```

**Comment by joelamb** [comment]
Thank you. I knew there would be a way to do it!
