### ISSUE TITLE
Can't use container as a class name

### ISSUE THREAD

**Issue by Dremora** [salsify/ember-css-modules#15]
Since updating to 0.3.0, it became impossible to use CSS class `container`. `{{styles.container}}` evaluates to Ember's container object and renders as `[object Object]`. There might be other properties with similar behavior.

**Comment by dfreeman** [comment]
Obviously a bug (and `container` has all kinds of appeal as a class name), but hopefully the workaround is apparent for the time being.

This should be fairly simple to fix on a case-by-case basis, but finding an approach that will play nicely across all the versions of Ember we'd like to support may be interesting, particularly spanning across the introduction of the owner API.

**Comment by dfreeman** [comment]
Just released 0.3.1 with a fix for this – please let me know if you have any trouble!
