### ISSUE TITLE
Override styles with ...attributes

### ISSUE THREAD

**Issue by gossi** [salsify/ember-css-modules#152]
I run into the following situation:

My component has this template:

```hbs
<div local-class="my-component" ...attributes>{{yield}}</div>
```

which I invoke like that:

```hbs
<MyComponent local-class="abc">hello world</MyComponent>
```

this renders as:

```html
<div class="_my-component_§$%?G _abc_FPfJ§%">hello world</div>
```

notice the order of classes here:

1. `my-component`
2. `abc`

And that order is not controllable. Means, if the component is defining a css property, it will have a higher specifity than what I define in `abc` and by that I don't make the property not overridable (and we want to avoid `!important`). 

I was wondering if this is supposed to be changed (or considered as by-design) and if yes, how? 

1) My idea would be to use something similar to the position of `...attributes` for glimmer itself:

```hbs
{{!-- my-component/template.hbs --}}
<div local-class="my-component" ...attributes>{{yield}}</div>

<div ...attributes local-class="my-component">{{yield}}</div>
```

And given where you put `...attributes` the class passed in from the outside is prepented or appended. But that is very hard in terms of consistency, you never know which component would allow overrides.

2) Overrides by default:

Given the initial structure, this is how it would render:

```html
<div class="_abc_FPfJ§% _my-component_§$%?G">hello world</div>
```

With that, adjustments from a higher level always take precendence and it would allow to override while giving decent defaults on the main implementation level.

What you think?

**Comment by dfreeman** [comment]
Contrary to popular belief, the order that class names are listed in in the `class` attribute on a DOM element doesn't impact how the styles are applied — you can see [a demonstration here](https://jsfiddle.net/k30nof5e/) 🙂 

The main thing that matters is the specificity of the source rule's selectorr, and if there's a tie there, then the order the rules are specified in the stylesheet is considered a tiebreaker.

**Comment by gossi** [comment]
Ah, I fooled myself by the location of the order: not in `class` but the `styles.css` file(s) itself. Since this is changeable with module ordering, that's fine. 

Thanks dan.
