### ISSUE TITLE
Importing node modules with postcss-import not working in @after-module stylesheets

### ISSUE THREAD

**Issue by max** [salsify/ember-css-modules#16]
I'm having trouble setting up something similar to [this example](https://github.com/salsify/ember-css-modules#importing-third-party-files).

I'm using the exact same setup and trying to both import `normalize.css` and `basscss` but it generates no output nor errors. If I try to `@import` from `app.css` instead of (`./thid-party/basscss`) it works as expected.

**Comment by max** [comment]
Here is [the example](https://github.com/max/things/tree/css-pipeline/app/styles).

**Comment by dfreeman** [comment]
This stumped me for a bit, but I think it's an issue with `postcss-import`. It's treating your imports as relative paths, so when it sees `@import "basscss";` in `basscss.css`, it thinks the file is trying to import itself, and it treats it as a no-op.

The two options I can think of off the top of my head would be:
 - rename or consolidate the files in `third-party` so they don't conflict with dependency names
 - set a custom [`resolve`](https://github.com/postcss/postcss-import#resolve) on the imports plugin to treat paths that don't start with `./` as absolute

**Comment by dfreeman** [comment]
I'll update the example in the README so it doesn't lead other folks down this path – sorry about that!

**Comment by max** [comment]
I can confirm this and it should have been obvious to me. Sorry for the noise. Your first workaround is totally acceptable given that you'd have to do that even without `ember-css-modules`.

Thanks for all your hard work. I'm playing around with it in a side project and hope to add it to Canvas fairly soon.

**Comment by ynnoj** [comment]
@dfreeman I'm encountering an issue in a setup similar to @max.

`Error: ENOENT: no such file or directory, open '/Users/J/git/stonecircle/stonecircle-web/tmp/simple_concat-input_base_path-EfXQNL3d.tmp/0/Users/J/git/stonecircle/stonecircle-web/tmp/cssmodules-input_base_path-uVypyluY.tmp/0/stonecircle-web/styles/third-party.css'`

I'm trying to `@import` some Basscss modules in `third-party.css` using `@after-module`. If I move the same import declaration to `app.css` (minus the `@after-module` at-rule) it works as expected.

**Comment by dfreeman** [comment]
@ynnoj It looks like an absolute path is being treated as relative somewhere in the pipeline, but beyond that I can't tell you much. Can you provide sample code or (ideally) a small repo that reproduces the problem?

**Comment by ynnoj** [comment]
@dfreeman I've created a test app (https://github.com/ynnoj/css-modules-test) that replicates the app showing the symptoms best I could. Yet it works exactly as expected in the test app and I'm unable to reproduce the issue 😒
