### ISSUE TITLE
Issues with Embroider staticHelpers: true

### ISSUE THREAD

**Issue by danwenzel** [salsify/ember-css-modules#162]
_Similar to https://github.com/salsify/ember-css-modules/issues/160_

Reproduction here: https://github.com/danwenzel/embroider-issues/tree/css-modules, but change `staticComponents: true` to `staticHelpers: true` in `ember-cli-build.js`

I've got the beta embroider version of ember-css-modules installed (1.3.0-beta.1). When turning on the `staticHelpers: true` embroider option, ember-css-modules cannot seem to find the `local-class` helper:

```
Error: Compile Error: local-class is not a helper
```

Also, I tried to debug by doing a stage-1-only build, but that threw a build error:

```
> STAGE1_ONLY=true ember b

Build Error (BroccoliBridgePlaceholder)

BroccoliBridge placeholder 'modules' was never fulfilled.
```

**Comment by dfreeman** [comment]
`staticHelpers` should now be supported in the `1.3.0-beta.2` release. Please give it a try and let me know if you run into any issues!
