### ISSUE TITLE
Skip processing chained classes?

### ISSUE THREAD

**Issue by max** [salsify/ember-css-modules#17]
How would you feel about the ability to skip chained classes:

```css
.my-component {}

.my-component.is-expanded {}
```

Turns into

```css
._hjk23_my-component {}

._hjk23_my-component.is-expanded {}
```

It's a fairly common practice to have state modifiers like that and chaining is encouraged because it increases specificity.

**Comment by max** [comment]
I realized I could use the `@global` syntax but that doesn't seem very idiomatic:

```css
.my-component {}

.my-component:global(.is-current) {}
```

**Comment by dfreeman** [comment]
This would be more in the realm of the underlying CSS modules implementation, and it's mostly out of the control of the addon code itself.

What's the motivator for this? Would something like one of the proposals in #1 help?

**Comment by max** [comment]
I'm closing this. For now using `{{styles.is-current}}` will work and I think #1 has the potential to make the same approach a lot nicer.
