### ISSUE TITLE
Best approach to style tagless components?

### ISSUE THREAD

**Issue by rickieshi** [salsify/ember-css-modules#178]
We are in process of gradually migrating components to use `tagName = ''` in preparation for glimmer components.

Currently I cannot find a good way to style tagless component when it is being used elsewhere.
```html
{{! route template}}
<SomeTagLessComponent local-class="some class names"/>
```
The local class is not being added, and I suspect this is related to the fact that component does not have a wrapper element?

What is the best approach to style such components?

**Comment by Turbo87** [comment]
you need to make sure that your tagless components are all using `...attributes`, otherwise the `local-class` won't be applied
