### ISSUE TITLE
localClassNames decorator not working for colocated classic components

### ISSUE THREAD

**Issue by nickschot** [salsify/ember-css-modules#179]
No error, just doesn't seem to do anything. Normal local-classes work fine.

> https://github.com/salsify/ember-css-modules/blob/master/packages/ember-css-modules/addon/mixins/component-mixin.js#L32-L55 likely needs to become aware of `setComponentTemplate` (since that's what colocation uses under the covers)

**Comment by dfreeman** [comment]
Since `localClassNames` is no longer a thing in ember-css-modules v2, I'm going to go ahead and close out this issue.
