### ISSUE TITLE
Strategy for importing legacy files

### ISSUE THREAD

**Issue by max** [salsify/ember-css-modules#18]
I'm trying to finally move Canvas over to `ember-css-modules`. My initial plan was to basically set it up so that the `diff` before and after the use of `ember-css-modules` would be 0 and then slowly start pulling things into the component pods with ✨ prefixes.

We have quite a few stylesheets with basic utility classes. What's your approach to skip the rewriting of classes for those files? I tried `@after-module` but that just guarantees load order.

**Comment by max** [comment]
`:global(.class)` works fine but it's a little tedious vs wrapping the entire file in "globals" – which is not ideal but it would be a smooth migration path.

**Comment by max** [comment]
Ah, I found the solution after scanning the README from top to bottom. If I set `postcss-nested` as a plugin in the `before` hook I can use:

```css
:global {
  .foo {}

  .bar {}
}
```

**Comment by dfreeman** [comment]
Yep, that's the approach I'd suggest 😄

Given that the README is getting pretty hefty, I've been considering getting a standalone doc site up and running, maybe using the `dummy` app from the repo like all the cool kids are doing these days. In particular, I think some kind of "cookbook" of common configuration concerns and combinations with other PostCSS plugins may help folks get up and running more quickly.

If you've got any thoughts on how that might be structured to make it easy to find stuff like this, I'd love your input.

**Comment by max** [comment]
I'll give it some thought!

**Comment by eccegordo** [comment]
How are you suppose to import postcss nested?

First I tried the naive approach

```
var EmberAddon = require('ember-cli/lib/broccoli/ember-addon');
module.exports = function(defaults) {
  var app = new EmberAddon(defaults, {
    cssModules: {
      plugins: {
        before: [
          postcss-nested
        ]
      }
    }
  });
  return app.toTree();
};

```

Then I tried 

```
npm install postcss-nested --save
```

and then tried to require at the top of the file, but that didn't work either

```
var EmberAddon = require('ember-cli/lib/broccoli/ember-addon');
var postcss-nested = require('postcss-nested');
module.exports = function(defaults) {
  var app = new EmberAddon(defaults, {
    cssModules: {
      plugins: {
        before: [
          postcss-nested
        ]
      }
    }
  });
  return app.toTree();
};
```

I am completely new to Post CSS and CSS Modules. Just trying to get some globals back in project similar to what Max is trying.

**Comment by eccegordo** [comment]
never mind the secret sauce was

```
var EmberAddon = require('ember-cli/lib/broccoli/ember-addon');
var nestedcss = require('postcss-nested');

module.exports = function(defaults) {
  var app = new EmberAddon(defaults, {
    cssModules: {
      plugins: {
        before: [
          nestedcss
        ]
      }
    }
  });
  return app.toTree();
};
```

You might want to provide a more complete example in the readme. Because legacy global css is something a lot of people new to this will probably try out right away and is a bit confusing at first.

**Comment by dfreeman** [comment]
@eccegordo The README has [several](https://github.com/salsify/ember-css-modules#simple-usage) [examples](https://github.com/salsify/ember-css-modules#importing-third-party-files) of importing plugins, but your point about documenting postcss-nested specifically as a migration strategy is well taken :)

Like I said a bit higher up in this thread, I think the README is too large and linear to be an effective way of communicating a lot of this stuff. I have the very beginnings of some dedicated documentation that will be better broken out into a high level overview, some kind of "common tasks" cookbook for things like this, and then dedicated sections for the nitty-gritty of configuration.

I'll create an issue (or maybe try out one of Github's fancy new Projects) to track the stuff that's going into that so I can get input from folks in the community as well as it's coming together.

**Comment by eccegordo** [comment]
@dfreeman no problem. Being new to Post CSS I was just tripped up by the require statement. If you do end up creating guide a small primer on post css might be handy for people coming into this. After reading up on it I get it now, basically babel for css.

Also, probably just need one line in the read me

```
var nestedcss = require('postcss-nested');
```

What wasn't clear was the require statement to get this working. And what is doubly confusing is that the usage example on the postcss-nested readme is that it just shows this

```
postcss([ require('postcss-nested') ])
```

I am a big fan of self contained code examples. Being able to cut and paste with a reasonable chance of it just working helps a lot.

Anyway, got this working in my project now. Seems really powerful.

**Comment by max** [comment]
@eccegordo Glad you got it working. I wanted to take a second and clarify why your initial attempts didn't work out since it's not `ember-css-modules` specific. You were trying to use a variable name with dashes in it which is not allowed in JS (`postcss-nested`) and the case of the first example you weren't importing the actual module.

Here are two _self contained code examples_ that essentially do the same thing:

```javascript
var EmberApp = require('ember-cli/lib/broccoli/ember-app');
var autoprefixer = require('autoprefixer');
var postcssNested = require('postcss-nested');

module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    cssModules: {
      plugins: [
        postcssNested
      ]
    },

    // ...
  });
	
  return app.toTree();
};
```

```javascript
var EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    cssModules: {
      plugins: [
        require('autoprefixer'),
        require('postcss-nested')
      ]
    },

    // ...
  });
  
  return app.toTree();
};
```

**Comment by eccegordo** [comment]
@max awesome, that second example makes much more sense now. So you can use the require statement directly inside the plugins array. Did not realize that.

**Comment by max** [comment]
Indeed. It really comes down to a preference in style. It can get very difficult to track down the require statements littered across a file which is why it's nice to assign them at the top.

Also, note that the "require statement" isn't all that special. This is essentially what you're doing:

```js
function require(module) {
	// Some fancy stuff happens here...
}

var eccegordo = require('eccegordo');
```
