### ISSUE TITLE
Support nested scss selectors

### ISSUE THREAD

**Issue by ikirkpat** [salsify/ember-css-modules#181]
I would like to be able to do something like this in my scss modules:

```
.some-class {
  ...
  &__some-element {
    ...
  }

  .child-class {
    ...
  }
}
```

I havn't seen this supported by this package

**Comment by buschtoens** [comment]
You need to install and [configure](https://github.com/salsify/ember-css-modules/blob/master/docs/POSTCSS.md) [`postcss-nested`](https://github.com/postcss/postcss-nested) for this. While you're at it, you can also add [`postcss-nested-ancestors`](https://github.com/postcss/postcss-nested-ancestors).

Alternatively, you could use [`ember-css-modules-sass`](https://github.com/dfreeman/ember-css-modules-sass) to have full Sass support.

**Comment by ikirkpat** [comment]
Awesom! I'll check it out. thanks!

**Comment by dfreeman** [comment]
Thanks for weighing in, @buschtoens! That's exactly what I'd suggest—this package doesn't intended to support any non-standard CSS notation other than what's part of CSS Modules out of the box.
