### ISSUE TITLE
use default classes in app.scss

### ISSUE THREAD

**Issue by mohitsud** [salsify/ember-css-modules#209]
I am not sure if this is a bug, feature request, or question.

I have the usual `app/styles/app.scss` which may contain a few css classes that I would like to re-use across my entire application.

When I want to use those styles in a component, I simply try `class="blah"` instead of using `local-class`. However, this does not seem to work.

Has anyone figured this out?

**Comment by buschtoens** [comment]
[Depending on your setup](https://github.com/salsify/ember-css-modules/blob/master/docs/PREPROCESSORS.md) the classes in `app.scss` are also getting scoped.

In your templates you could use [`class={{local-class ... from="my-app/styles/app.scss"}}`](https://github.com/salsify/ember-css-modules#programmatic-styles-access). And in your styles you could use [`@value` & `composes`](https://github.com/salsify/ember-css-modules#styling-reuse).

If you want to make the classes in `app.css` truly global and opt-out of scoped name generation, you can use the [`:global` pseudoselector](https://github.com/salsify/ember-css-modules#global-classes).

**Comment by mohitsud** [comment]
Thanks for the reply and explaining a solution.
