### ISSUE TITLE
Embroider: Route CSS modules do not work

### ISSUE THREAD

**Issue by Turbo87** [salsify/ember-css-modules#211]
In the https://github.com/rust-lang/crates.io codebase we are using `ember-css-modules` for both colocated components, and route templates. With the regular build this works fine, but when built with https://github.com/embroider-build/embroider/ (via `USE_EMBROIDER=y`) only the component CSS modules seem to be used. The `class` attributes for the route templates are all empty.

**Comment by dfreeman** [comment]
Thanks for filing this! I'm not sure I'll have the opportunity to dig in to this immediately (most of my on-the-clock OSS time for the rest of the year is earmarked for typed-template stuff), but hopefully this will be a small fix and I'll find some time to knock it out.
