### ISSUE TITLE
local-class not showing

### ISSUE THREAD

**Issue by fernandaparisi** [salsify/ember-css-modules#212]
This is my `template.hbs` file:
![Screen Shot 2020-11-18 at 02 14 17](https://user-images.githubusercontent.com/1117355/99487057-48279280-2944-11eb-987f-ddd5b69bfaf9.png)

And this is the code once generated:
<img width="289" alt="Screen Shot 2020-11-18 at 02 15 24" src="https://user-images.githubusercontent.com/1117355/99487114-5fff1680-2944-11eb-9572-bd6ed6eedbb4.png">

Notice that only the attribute in which local class equals the component name (`tooltip`, in this case) prints the namespaced class. 

using `"ember-css-modules": "^1.3.1"`

**Comment by buschtoens** [comment]
What does your css file look like? What are the exact file paths?

Try restarting `ember serve` and clearing your browser cache. I recently had a case where a newly added local-class was included in the bundled CSS, but not in the JS bundle, presumably because of browser cache issues.

**Comment by fernandaparisi** [comment]
@buschtoens I did just that: restarded the server, cleaned browser cache and also removed a `/tmp/` folder that was lying around on the project. it did solve the issue, thanks
