### ISSUE TITLE
Deprecation use of Reopening the Ember.Component super class

### ISSUE THREAD

**Issue by makannew** [salsify/ember-css-modules#246]
Bellow deprecation warning appears on console:

"Reopening the Ember.Component super class itself is deprecated. Consider alternatives such as installing event listeners on the document or add the customizations to specific subclasses. [deprecation id: ember.component.reopen]"

**Comment by Turbo87** [comment]
see #237

**Comment by makannew** [comment]
I'm closing this in favor of https://github.com/salsify/ember-css-modules/issues/237
