### ISSUE TITLE
Subclassing support?

### ISSUE THREAD

**Issue by max** [salsify/ember-css-modules#25]
Unsure if this is a thing that goes against CSS Modules. But in case it's a bug. Would you expect subclassing to work?

```js
/* thing/components/my-component/component.js */

export Ember.Component.extend({
  classNameBindings: ['styles.component'],
  foo: 'bar'
});
```

```js
/* thing/components/some-component/component.js */

import MyComponent from 'thing/components/my-component/component';

export MyComponent.extend({
  foo: 'beep'
});
```

If subclassing were supported I'd expect to get all the styles from `MyComponent` in `SomeComponent`.

**Comment by dfreeman** [comment]
In your example above, does `some-component` inherit `my-component`'s template? I'd expect to need to do something like this for that to work:

```js
import MyComponent from 'thing/components/my-component/component';
import layout from 'thing/components/my-component/template';

export MyComponent.extend({
  layout,
  foo: 'beep'
});
```

Styles for a component/controller are essentially resolved in the same way as templates are, so in general I wouldn't expect subclassing to work unless you explicitly import the parent component's styles.

**Comment by max** [comment]
Makes sense. I didn't draw the parallels to templates because in theory styles could work (by merging and overriding) but this sounds like a nightmare so 👍 .
