### ISSUE TITLE
Not compatible with Ember 4

### ISSUE THREAD

**Issue by NullVoxPopuli** [salsify/ember-css-modules#259]
in ember 3.28, I get a deprecation warning about using the Ember global -- I presume this is from an old version of ember-cli-htmlbars

**Comment by NullVoxPopuli** [comment]
I think I need to dig deeper into this.

**Comment by dfreeman** [comment]
We have tests passing in CI against release/beta/canary channels, so I don't think it's likely that we have a blanket incompatibility with Ember 4.

**Comment by NullVoxPopuli** [comment]
Yeah. Maybe a red herring i saw
