### ISSUE TITLE
Introduction to ember-css-modules at Global Ember Meetup

### ISSUE THREAD

**Issue by taras** [salsify/ember-css-modules#27]
Would someone familiar with the project be interested tell in giving an `Introduction to ember-css-modules` at Global Ember Meetup on June 11th? 

An `introduction to <addon>` talk answers the following questions:
1. What problem is this addon looking to solve?
2. How does a developer get started?
3. What does a developer need to know to effectively use the addon? 

The recording will be edited and we'll create  video like this https://vimeo.com/album/3607049 that you can use as an introduction to this addon.

**Comment by dfreeman** [comment]
@taras I'd love to, but am likely to be traveling that weekend. Would it be possible to shoot for the next meetup after June 11? I'm also @dfreeman on the Ember Slack, if it's easier to coordinate there.

**Comment by taras** [comment]
Sure! July 2nd will be the next event. Would you like me to put on for that date?

**Comment by dfreeman** [comment]
July 2nd sounds great. Thanks!

**Comment by rox163** [comment]
Is the video for this out yet? Interested in applying this to our project.

**Comment by dfreeman** [comment]
@rox163 Not yet — we ended up pushing back to a later date. I'll post back here with a link once it's up!

**Comment by dfreeman** [comment]
@taras I'm going through and cleaning up some old issues right now. If you still think this would be valuable, can you ping me in Slack? This seems to have gone stale a couple of times in the interim :)
