### ISSUE TITLE
Ability to override scoped name generator

### ISSUE THREAD

**Issue by Dremora** [salsify/ember-css-modules#3]
Allow passing custom `generateScopedName` to `broccoli-css-modules`. Use case: we have a deeply nested component hierarchy, and including path in the generated class name would improve our DX.

**Comment by dfreeman** [comment]
Totally reasonable use case, but I probably won't have the chance to get to it in the immediate future. It should be relatively straightforward to pass through, though – I'd happily accept a PR if you get to it in the meantime.

**Comment by dfreeman** [comment]
Just published support for this in 0.3.0.
