### ISSUE TITLE
Stupid Question: Usage with link-to helper

### ISSUE THREAD

**Issue by duro** [salsify/ember-css-modules#33]
I am struggling to find the right syntax to use this the built-in `link-to` helper. I have tried:

`{{#link-to 'routeName' class={{styles.class-name}}}}Label{{/link-to}}`
`{{#link-to 'routeName' class="{{styles.class-name}}" }}Label{{/link-to}}`
`{{#link-to 'routeName' class=styles.class-name }}Label{{/link-to}}`

And none of these work. Your hep is appreciated.

**Comment by duro** [comment]
Never mind. User error.

What I landed on was:

`{{#link-to 'routeName' class=styles.class-name }}Label{{/link-to}}`

The exposes a new question. How would I add multiple classes if they were needed?

**Comment by dfreeman** [comment]
For now, you'd use Ember's `concat` helper, like:

```hbs
{{#link-to 'routeName' class=(concat styles.class-one ' ' styles.class-two)}}Label{{/link-to}}`
```

When #31 lands, you'd be able to do this instead:

```hbs
{{#link-to 'routeName' local-class='class-one class-two'}}Label{{/link-to}}
```

**Comment by duro** [comment]
Awesome. Thanks!
