### ISSUE TITLE
No styles prop in controller .. but present in component js files

### ISSUE THREAD

**Issue by annamalai-saro** [salsify/ember-css-modules#37]

**Comment by dfreeman** [comment]
Unfortunately there's not much I can do to help with this little to go on.
 - What version of Ember are you using?
 - What version of ember-css-modules are you using?
 - What have you tried? Where is the CSS and JS for your controller vs your component?
A gist or (much better) a git repository reproducing the issue would make it a lot clearer what the problem might be and how it can be fixed.

**Comment by annamalai-saro** [comment]
@dfreeman  I understand your needs .. I'll try to reproduce and notify you

**Comment by dfreeman** [comment]
Based on the change you submitted in #38, I've [updated the README](https://github.com/salsify/ember-css-modules#classic-structure-applications) to hopefully clarify where to put CSS in a "classic" structure application. Does that help?

**Comment by annamalai-saro** [comment]
@dfreeman  It is super clear !  The problem is not about structuring , its about accessing  styles in the `hbs` files

**Comment by dfreeman** [comment]
If your file structure is correct, either of the following should work equivalently for a route template:

```hbs
<div local-class="my-class"></div>
<div class={{styles.my-class}}></div>
```

If the change you submitted in PR #38 works for you, then that means you would have the CSS for your application route at `app/styles/controller/application.css`, whereas the documentation states that it should be `app/styles/application.css`, with no `controller` directory.

We have an [acceptance test](https://github.com/salsify/ember-css-modules/blob/master/tests/acceptance/styles-lookup-test.js#L9) that verifies that such a structure works, given [this template](https://github.com/salsify/ember-css-modules/blob/master/tests/dummy/app/templates/classic-route.hbs
) and [this CSS](https://github.com/salsify/ember-css-modules/blob/master/tests/dummy/app/styles/classic-route.css). If you're confident everything is in the right place and you're still unable to access the local styles, could you provide a link to a repository demonstrating the issue?

**Comment by annamalai-saro** [comment]
@dfreeman Perfect !
