### ISSUE TITLE
Ampersand operator doesn't works in addon

### ISSUE THREAD

**Issue by b-ponomarenko** [salsify/ember-css-modules#49]
For example, I have styles:
`.button {`
`  &:hover { color: red }`
`}`
and I expect `.button:hover {color:red}`, but ember-css-modules doesn't compile it.
For more examples I create a simple addon, please check [this link](https://github.com/b-ponomarenko/test-ember-css-addon)

**Comment by b-ponomarenko** [comment]
I find solution, you can add call `postcss-nested` plugin from `index.js` file.
Example:
<pre>
'use strict';
const nested = require('postcss-nested');

module.exports = {
  name: 'ember-addon-css',
  options: {
  	cssModules: 
  	{
      plugins: [
          nested()
      ]
    }}
};
</pre>

**Comment by dfreeman** [comment]
The only syntax this addon provides is the bits that are relevant to modules — `@value`, `composes:`, `:global(...)`, etc.

If you want support for other things like nested class syntax, you can [add PostCSS plugins](https://github.com/salsify/ember-css-modules#plugins). For your specific example here, you could use [`postcss-nested`](https://github.com/postcss/postcss-nested), or if you're looking for a lot more stuff, you could check out [cssnext](http://cssnext.io/).

**Comment by dfreeman** [comment]
@b-ponomarenko Ah, your comment only showed up after I posted mine. That's exactly right.
