### ISSUE TITLE
Missing caching strategy

### ISSUE THREAD

**Issue by jzaefferer** [salsify/ember-css-modules#50]
On our ember-cli app we're seeing these deprecations:
```
DEPRECATION: ember-cli-htmlbars-inline-precompile is opting out of caching due to an AST plugin that does not provide a caching strategy: `ember-css-modules`.
DEPRECATION: ember-cli-htmlbars is opting out of caching due to an AST plugin that does not provide a caching strategy: `ember-css-modules`.
```
I don't quite understand what's going on. In https://github.com/ember-cli/ember-cli-htmlbars/issues/92 I was asked to file an issue here.

**Comment by dfreeman** [comment]
@jzaefferer This was fixed in 0.4.2. Can you confirm you're on the most up to date version of ember-css-modules?

**Comment by jzaefferer** [comment]
I'm probably not. Not sure why I didn't think of checking that first. Testing that now.

**Comment by jzaefferer** [comment]
That helped. Thanks!
