### ISSUE TITLE
Incompatible with ember-cli-sass

### ISSUE THREAD

**Issue by stephencarr** [salsify/ember-css-modules#61]
I've posted this issue in `ember-cli-sass` too, I can't figure out what the problem is, just know that the two addons don't work together.

```
Error: File not found: /app/styles/app.scss
in any of the following include paths:
```

A fresh app with latest `ember-cli-sass` works fine. When `ember-css-modules` is installed the above error occurs. Would be nice to have both play well with each other.

**Comment by dfreeman** [comment]
There's [a section of the README](https://github.com/salsify/ember-css-modules#other-preprocessors) dedicated to interoperability between ember-css-modules and other preprocessors like Sass. Have you read through that and followed the directions there?

(aexmachina/ember-cli-sass#147 should probably be closed, as it's definitely not an issue on that end.)

**Comment by stephencarr** [comment]
Thanks for your reply. I've tried both options from the readme and neither work for me. I will try from a fresh app with just the required dependencies and try again.
