### ISSUE TITLE
Files processed more than once

### ISSUE THREAD

**Issue by alexlafroscia** [salsify/ember-css-modules#63]
I'm noticing that some of our CSS files are being run through PostCSS more than once.  I'm not sure if it's an issue at this level or at the `broccoli-css-modules` level, but a particular plugin that warns about missing retina images fires multiple times for this one file:

![screen shot 2017-01-20 at 5 52 49 pm](https://cloud.githubusercontent.com/assets/1645881/22170926/5c2962e4-df39-11e6-9cd3-edf12d96773f.png)

If it weren't for the noisy warning, I wouldn't have noticed.

I dug in a bit to see if the issue was with the `postcss` plugin (it's one that I wrote) and as far as I can tell, it's not an issue with the plugin; a `debugger` set to break when that particular file is first loaded up catches 5 separate times, indicating to me that `postcss` is processing the file 5 times.

What's interesting is that the same plugin warns for other files, but only once. I have no great way of knowing how many files are processed multiple times, since it just happens to be that a warning is generated here that's easy to see.

**Comment by alexlafroscia** [comment]
Using a second plugin that also throws warnings, I was able to see that it, too, processed the file 5 times:

![screen shot 2017-01-20 at 6 04 11 pm](https://cloud.githubusercontent.com/assets/1645881/22171017/dcaf35fa-df3a-11e6-8be9-e58fb71a981c.png)

**Comment by alexlafroscia** [comment]
Interestingly (and probably not coincidentally) there are 5 instances where the class causing the warning is composed from in another file...

**Comment by jasonmit** [comment]
@alexlafroscia can you reproduce this with a fresh app?

**Comment by alexlafroscia** [comment]
@jasonmit here's a repo that reproduces the bug. It definitely has to do with the class that causes the warning being composed from.

https://github.com/alexlafroscia/ember-css-modules-issue-63

I created three components, a base and two children. The base component has a class that throws a PostCSS warning, and the two child components both compose from that class.  If you run `ember serve`, you'll see the error is reported three times.

**Comment by dfreeman** [comment]
Sorry @alexlafroscia I've been traveling the past few days and am just now starting to catch up on the pile of un-dealt with notifications. In theory `broccoli-css-modules` caches every file it processes during a build pass, but it's entirely possible there's something wrong there.

I probably won't have a chance to look very deeply tonight, but I'll definitely revisit one evening this week. I'm guessing this may end up being an always-exciting game of "spot the race condition"

**Comment by alexlafroscia** [comment]
No problem! Not at all. If I get some time this week I'll try to investigate it a bit too.

**Comment by dfreeman** [comment]
Big thanks to @rondale-sc for fixing this in https://github.com/salsify/broccoli-css-modules/issues/4! 

The next version of ember-css-modules that goes out will have the version constraint bumped, but for now a fresh install should pick up the fix.
