### ISSUE TITLE
Ember 2.12 DEPRECATION causing really slow builds

### ISSUE THREAD

**Issue by haldiggs** [salsify/ember-css-modules#70]
if anyone knows how to fix this issue I'd appreciate it. I cannot do a pull from my office. This project is not the only one throwing this type of issue but for some reason they really pause the build of the project.

DEPRECATION: Ember CLI addons manage their own module transpilation during the `treeForAddon` processing. `ember-css-modules` (found at `\node_modules\ember-css-modules`) has overridden the `this.options.babel` options which conflicts with the addons ability to transpile its `addon/` files properly. Falling back to default babel configuration options.

DEPRECATION: Ember CLI addons manage their own module transpilation during the `treeForAddon` processing. `ember-css-modules` (found at `\node_modules\ember-css-modules`) has overridden the `this.options.ember-cli-babel.compileModules` value which conflicts with the addons ability to transpile its `addon/` files properly.

**Comment by dfreeman** [comment]
Hi @haldiggs — a couple things 🙂 
 - This should have been fixed in v0.6.5 (see https://github.com/salsify/ember-css-modules/issues/64 and https://github.com/salsify/ember-css-modules/commit/434112b1ebbe19daad658ae54f4bbbee43b3e7c1) — can you confirm you're on the latest version?
 - Even in versions prior to v0.6.5, this particular deprecation shouldn't have any impact on your build performance that I'm aware of. Are you sure this is the culprit?

**Comment by haldiggs** [comment]
well I guess I can't swear it is whats slowing the builds down, but when I backed off from 2.12.x to 2.11.x the build speeds went back to normal. 

The other tools that were also having this same issue also had to be fixed; ember-forms, ember-bread-crumbs and others. So this was the only DEPRECATION issue I had left. 

for now I am back on 2.11.x so no worries. I'm sure it will work itself out in this case.

**Comment by dfreeman** [comment]
Whenever you do get back to CLI 2.12.x, let me know if you still see the deprecation warning and/or slowness with v0.6.5+ of ember-css-modules. We're using that combination in several production apps (some of them pretty large) and haven't had any issues, but it's always possible you're hitting a case we're not 🙂

**Comment by haldiggs** [comment]
will do
