### ISSUE TITLE
Using Less mixins and functions with css-modules

### ISSUE THREAD

**Issue by wattyrevBT** [salsify/ember-css-modules#73]
I have a UI Kit built in less that provides basic styling and provides less variables, functions, and mixins. This UI Kit is used in several Ember apps. My current approach to integrating this alongside css-modules is to have this sort of setup:

## File Structure
```
>styles
    >components
        user-avatar.less
    app.less
    index.less
```

## app.less
```css
@import '../path-to/ui-kit.less';
```

## Ember CSS Modules Options:
```javascript
cssModules: {
            intermediateOutputPath: 'app/styles/app.less',
            extension: 'less',
            postcssOptions: {
                syntax: postcssLess
            }
},
```

What I end up with is a single less file that begins by importing the UI Kit. This works great for accessing UI Kit variables, but not so much for using UI Kit mixins and functions. If I do something like:
```css
.some-selector {
    .border-bottom-radius(40px);
}
```
or
```css
.some-selector {
    .clearfix;
}
```
I run into problems because ember-css-modules tries to scope these, just like regular classes. The `:global` bit doesn't seem to work in these instances either:
```css
.some-selector {
    :global .border-bottom-radius(40px);
}
```

The mixins part isn't a big deal to me, but the loss of functions could be a problem.

Is there any existing process that can help me here? I'm imagining that it would be nice to have a way to escape these lines, be it with the `:global` prefix, or handling it in a similar way to less, using `~"my escaped content"`, where less will simply remove the tilde and quotes around this content, then leave it alone.

**Comment by wattyrevBT** [comment]
I think I found a solution that works for me. For functions, I can namespace all my functions as `.fn_my-function`. Then, I can override the `generateScopedName` method in cssModules options and ignore any classnames with that `fn_` prefix.

If I decide I need mixins, I can do the same thing, but remove the prefix during cssModules processing.


What I was really hoping for was that I could just do this logically in the `generateScopedName` method. It has access to the class name and the contents of the file. The only thing missing is a line number. If I had that, I could look in the file at the specific use of the class name and determine if it is a mixin or function. I poked around through ember-css-modules and broccoli-css-modules to see if I could get that information, but I came up short.

**Comment by dfreeman** [comment]
Hi @wattyrevBT,

Unfortunately you're running up against the edge of explored territory right now... I don't know of many other people out there using ECM with Less.

>  The :global bit doesn't seem to work in these instances either:

I'd love it if `:global fn(...);` worked, but it looks as though `postcss-less` doesn't parse that into anything meaningful—you just end up with something like this, with the actual function call just dangling off as an extra ignored token:

```js
Declaration {
  prop: 'global',
  value: '',
  raws: { before: '', between: ' fn(...)' }
}
```

> The only thing missing is a line number. If I had that, I could look in the file at the specific use of the class name and determine if it is a mixin or function. I poked around through ember-css-modules and broccoli-css-modules to see if I could get that information, but I came up short.

The information available for scoping names is unfortunately fixed at the level of [postcss-modules-scope](https://github.com/css-modules/postcss-modules-scope), so from this end of things we don't have the ability to supply that additional info. 

> I think I found a solution that works for me. For functions, I can namespace all my functions as .fn_my-function

I'm sad to say it, but this is the best near-term option I can think of at this point. Ultimately to get this working properly with `:global`, I think you'd need to open a PR with `postcss-less` to change how they parse functions and mixins with extra preceding tokens like `:global` — I'd be surprised if anyone was relying on the current behavior, but I don't have a good sense of how involved a change that would be.

**Comment by dfreeman** [comment]
@wattyrevBT I'm going to go ahead and close this out, since there isn't anything actionable that can happen on this end.
