### ISSUE TITLE
Component integration tests are failing

### ISSUE THREAD

**Issue by alvinvogelzang** [salsify/ember-css-modules#74]
I think I've already mentioned this issue a while ago in the slack channel. All my component integration tests are failing when I use localClassNameBindings. I'm not sure if we need to label this as a bug but it is quite annoying. Maybe we need to add some instructions to the readme about this. 

The following error is showing up: `Cannot read property 'is-disabled' of undefined`. 

'is-disabled' is the dasherized name of my bind property. The error comes from the buildBindings function in the component-mixin.js. This function is looking for true and false classes based on the component.get('__styles__') property. Because component.get('__styles__') is empty / undefined in the integration test we're receiving this error.

What I've done to make the test succeed is the following.

In the test I've set the `__styles__` property like this:

```
this.set('__styles__', {
   'is-disabled': '_is-disabled_mjzj8'
});
```

And I'm passing the `__styles__` property as `__styles__` to the component like this:

```
this.render(hbs`{{edit/preformatted-widget isDisabled=true __styles__=__styles__}}`);
```

Now everything works as expected but it feels quite devious. I'm wondering if it is desired to let all those tests fail when someone is using localClassNameBindings or if we can make a baked in default / solution for it.

Another thing I'm wondering is if there is a better / easier way to make these tests pass.

**Comment by dfreeman** [comment]
Hi @alvinvogelzang — thanks for reporting this! It looks like the issue here is that the resolver is being instantiated before ember-css-modules is able to `reopen` it to tweak how styles are resolved. This should be fixable from this end with a little bit of cleanup I've been meaning to do anyway.

In the meantime, you should be able to work around this by adding this line to your `app/resolver.js`:

```js
import 'ember-css-modules/extensions';
```

**Comment by alvinvogelzang** [comment]
@dfreeman perfect, the workaround solves the problem for now. Thanks for your fast response :-)

**Comment by dfreeman** [comment]
You should be able to remove that extra `import` as of v0.7.3 — please give me a shout if you run into any other issues :)
