### ISSUE TITLE
Module Unification

### ISSUE THREAD

**Issue by dfreeman** [salsify/ember-css-modules#76]
Currently ECM will cause build errors when installed in a MU app. That should be relatively easy to fix in terms of the existing status quo, but MU opens the door to a lot of improvements in terms of how ember-css-modules functions:
 - static local class names can be determined at build time, making `local-class` a zero-cost abstraction for non-dynamic values
 - monkey patches for `Resolver`, `Controller` and `ComponentLookup` can be dropped
Eventually this will leave the `local-class` helper and the `localClassNames` extension for components as the only remaining runtime code, which also constitutes a good step toward #69.

**Comment by karellm** [comment]
Any update on that front? Module Unification seems to be coming fast and I started playing with it by curiosity and indeed `ember-css-modules` breaks the build.

**Comment by NullVoxPopuli** [comment]
after installing this addon into a MU app, I get the following error when I try to build:
```
Build failed.
Build Error (SassCompiler)

File not found: /src/ui/styles/app.scss
in any of the following include paths:
  /home/me/Development/NullVoxPopuli/emberclear/tmp/sass_compiler-input_base_path-WZ9ku5Tb.tmp/0
  /home/me/Development/NullVoxPopuli/emberclear/tmp/sass_compiler-input_base_path-WZ9ku5Tb.tmp/1


Stack Trace and Error Report: /tmp/error.dump.d64f2ef6078dfc94765888b93047f89d.log
```

it says src/ui/styles/app.scss doesn't exist....
but...

![image](https://user-images.githubusercontent.com/199018/40417659-3fd3dd5a-5e4e-11e8-8c2f-b1b0de84f7e2.png)

**Comment by dfreeman** [comment]
I started a pass at MU support a couple months back — the build changes needed weren't too bad, but the way the MU resolver functions is going to require some work in the runtime too. I'm hoping to come back to this sometime in the near future 🙂

**Comment by dfreeman** [comment]
Spent a bit of time on this today, investigating the feasibility of getting MU support with the way we do dynamic resolution at runtime in the current version of ECM. While it's definitely possible, it's ultimately going to be somewhat complicated by things like local lookup, and between that and issues like #98, I think the time will be better spent building toward the more static approach described above. That should allow us to:
 - support MU projects
 - support the template-only Glimmer components feature
 - provide build-time validation that (static) local classnames exist
 - insert static local classnames at build time rather than deferring to runtime

My goal is to start working toward this over the next few weeks; I'll post progress here if/when there's anything worth mentioning.

**Comment by karellm** [comment]
@dfreeman I was wondering if there was any update on this? I'd really love to use this plugin with MU! Thanks :)

**Comment by dfreeman** [comment]
Hi @karellm! The groundwork for more static analysis described above has landed, and the plan as of now is to get a stable 1.0 release out the door (1.0.0-beta.1 just went out) and then come back and land some sort of initial MU support shortly thereafter.

Supporting MU has been a moving target for a while, and this addon definitely goes off the beaten path somewhat in terms of how its build-time processing works. Because of that, I've been waiting for things to solidify there a bit, but rest assured this issue is still on my radar 🙂

**Comment by dmzza** [comment]
I'm using SASS in my module unification app, so I also had to fork [dfreeman/ember-css-modules-sass](https://github.com/dfreeman/ember-css-modules-sass) to make a small change to the output path.

My branch is available here: [dmzza/ember-css-modules-sass#feature/module-unification](https://github.com/dmzza/ember-css-modules-sass/tree/feature/module-unification)

I'm not making a PR yet because module unification has been postponed.

**Comment by NullVoxPopuli** [comment]
while MU has been postponed, it's still maybe likely that we're keeping the src folder. 

based on the diff: https://github.com/dfreeman/ember-css-modules-sass/compare/master...dmzza:feature/module-unification @dmzza, I think you totally should open a PR :)

**Comment by dfreeman** [comment]
@NullVoxPopuli Given that we don't quite know what it will look like from a preprocessor's perspective when it receives a `src` dir, how ember-cli will indicate what sort of app structure is being processed, etc, I'd be a little reluctant to publish code that makes assumptions about any of that.

@dmzza The good news is you don't actually need to fork `ember-css-modules-sass` to change that value—you can write it directly in the `ember-cli-build.js` for your app, if you want:

```js
new EmberApp(defaults, {
  // ...
  cssModules: {
    intermediateOutputPath: 'src/ui/styles/app.scss'
  }
});
```

**Comment by dfreeman** [comment]
Since the core team's plan is [not to move forward with Module Unification](https://blog.emberjs.com/2019/03/11/update-on-module-unification-and-octane.html), I'm going to close out this issue. As template imports evolve in the future, we'll reassess and figure out the best path forward for ember-css-modules. Thanks for your input, everyone!
