### ISSUE TITLE
`headerFiles` does not support file extension

### ISSUE THREAD

**Issue by alexlafroscia** [salsify/ember-css-modules#79]
I noticed that the `headerFiles` (and presumably `footerFiles`) fails if the file extension is provided in the listed paths. This is totally fine, but you might want to document that -- you _can_ provide the extension when importing from a file, and the docs say that the same paths can be placed in either location.

**Comment by dfreeman** [comment]
Ah, I'd totally forgotten that specifying the extension was allowed for imports. I'll update the those options to allow it there too.
