### ISSUE TITLE
Question about acceptance testing

### ISSUE THREAD

**Issue by rhysburnie** [salsify/ember-css-modules#80]
Hello,

I have a question.

When acceptance testing an app and components it is typical do do stuff like:

`const someElement = find('.some-element')` or `click('.some-button')`

I'm wondering how you go about selecting elements that are using `local-class` is there a utility or something that allows you to get the correct hashed classname for usage in acceptance tests?

**Comment by akashdsouza** [comment]
I believe it would be better to use data-* attributes for testing rather than classes. You can look into https://github.com/simplabs/ember-test-selectors/

**Comment by rhysburnie** [comment]
@akashdsouza thanks... seems like a great solution even without css modules :)

**Comment by dfreeman** [comment]
@akashdsouza is right on the money—exactly what I would have suggested 🙂
