### ISSUE TITLE
expand {{local-class}} to get classes from other files

### ISSUE THREAD

**Issue by kellyselden** [salsify/ember-css-modules#86]
```hbs
{{! app/components/my-component/template.hbs }}
<div class="{{local-class 'hello-class' 'my-app-name/styles/headers'}}">Hello, world!</div>
```

I think this makes sense, but would it be possible?

**Comment by dfreeman** [comment]
This is actually already possible:

```hbs
<div class="{{local-class 'hello-class' from='my-app-name/styles/headers'}}">
```

I'd been avoiding documenting it in an attempt to curtail complexity in possible future work for making local class resolution more static, but realistically it's probably worth making public.

Any interest in opening a PR to the README? 🙂

**Comment by brunomacf** [comment]
@dfreeman how this resolution works inside an addon that also expose some styles from `app` foder? So suppose i have an addon with 2 components living in `addon/components/comp-A` and `addon/components/comp-B`. In comp-B i want to do something like `<div class="{{local-class 'comp-A-class from='addon/components/comp-B/styles'}}">` but it can't get resolved correctly. I can do stuff like `@import 'my-css-file` when my-css-file is inside `app/styles` but i can't figure it out how to resolve files that lives inside `addon` folder.
