### ISSUE TITLE
@localClassName and @localClassNames decorators

### ISSUE THREAD

**Issue by buschtoens** [salsify/ember-css-modules#88]
Since ember-decorators added [@className and @classNames decorators](https://github.com/ember-decorators/ember-decorators/blob/68362ab0ae3c7f2b7351ec31eac0f23a5bc38077/addon/component/index.js#L43-L121), I think it's time for us to do the same.

Your original comment for reference: https://github.com/ember-decorators/ember-decorators/issues/133#issuecomment-316711907

I can try my hand at a PR, if you want. :smile:

**Comment by dfreeman** [comment]
@buschtoens a PR would be great! ❤️

**Comment by buschtoens** [comment]
https://github.com/ember-decorators/ember-decorators/issues/145#issuecomment-344830650 suggested releasing these decorators as `@ember-decorators/css-modules` for now. This way we can experiment with the API a bit and possibly break things without requiring major version bumps for the main `ember-css-modules` package. We also don't impose our decorator preference onto the whole e-c-m user base in terms of file size.

**Comment by dfreeman** [comment]
I have a sense that there's basically a race between the adoption of ES classes and the move toward Glimmer components that will impact where it makes sense for these decorators to live long-term.

 - if use of ES classes catches on in the community first (which seems not-unlikely given that the remaining blockers are pretty quickly disappearing, and there was positive reception to @pzuraq's blog post), then ultimately I think the decorators should become the blessed path for doing `localClassName` stuff with ECM
 - if Glimmer components in the context of Ember apps picks up sooner, then the need for `localClassNames` goes away, so the point becomes (mostly) moot

Either way, I think experimenting in `@ember-decorators/css-modules` seems like a good first step and will allow for faster iteration 👍
